### ISSUE TITLE
push embedding model all-mpnet-base-v2

### ISSUE THREAD

**Issue by joehoover** [replicate/all-mpnet-base-v2#1]
Minion, among others, have expressed interest in using embedding models on replicate. 

Minion requested this model and it would be a good model for us to push regardless, as it's among sota for open-source embedding models. 

This issue will be complete when:

```[tasklist]
### Tasks
- [x] inference code is complete
- [ ] https://github.com/replicate/all-mpnet-base-v2/issues/3
- [x] cog model is pushed
- [x] inference via replicate is complete
- [ ] fine-tuning via replicate is complete
- [x] README is written
- [ ] Tweets are written
- [ ] Tweets are approved
- [ ] Tweets are scheduled
```
